### ISSUE TITLE
treasure chest goes down(to the lower playfield) and up(from the lower playfield)

### ISSUE THREAD

**Issue by remdwaas** [Shoopity/MonkeyIslandPinball#27]
The treasure chest that goes down to the lower playfield and up again. this is also still an issue on my halo table so i don't have a fix for it. When it's finished i put it back to the original place but this goes wrong:

sub chestright
treasurechest.z = "-0,5" 'was -0,8
end sub

**Comment by Shoopity** [comment]
I guess I'm not seeing the issue here.  The chest seems to move just fine to me.  Is it not going back to where it's supposed to without calling ChestRight?  Are you looking for a solution where you don't have to call that?

**Comment by Shoopity** [comment]
Due to the nature of how we're moving the lid, it has to be done this way.  Although, I would rather do it in the moving code itself instead of a 1.5 seconds later.  What's happening is, the id is starts at Z = -86 (or possibly as low as -89, I haven't done the math).  So on the first tick of the up timer, it moves to -82, then -78 and so on.  Because you're moving it at 4 units per tick, it's possible it could get to -2, which is less than -1, so at the next tick it still moves and jumps all the way up to +2.  Then at the next tick, it disables the timer, leaving it at +2.  So you have to manually move it back down to the position you want it.

What's wrong with leaving it higher than it used to be?  I tried using cabinet mode and didn't see anything myself, but I don't have a 32" screen to really test it on, so I understand it may look horrible.

The only change I would suggest making (which I'll make if you tell me to do it), would be inside the moving the sub itself:
sub ChestupTimer_Timer()
	ChestdownTimer.enabled = 0
	If treasurechest.z < -1 Then
		treasurechest.z = treasurechest.z + 4
	Else
		ChestupTimer.Enabled = 0
	End If
	If treasurechest.z > -0.5 Then tresurechst.z = -0.5
end sub

Then you don't have to have an additional sub, and you don't have to move the lid 1 second later.  You want me to do it that way?

**Comment by Shoopity** [comment]
Personally, I would suggest making the origin of the lid be at the top of the lid (which would mean placing the lid differently on the table... although that could be handled in the code), then instead of lowering the lid, you rotate it on the X axis so it's opening up... like a treasure chest lid.

**Comment by remdwaas** [comment]
when you go further again, can you please change it then to:
sub ChestupTimer_Timer()
ChestdownTimer.enabled = 0
If treasurechest.z < -1 Then
treasurechest.z = treasurechest.z + 4
Else
ChestupTimer.Enabled = 0
End If
If treasurechest.z > -0.5 Then tresurechst.z = -0.5
end sub

**Comment by Shoopity** [comment]
I've done that.  I also went ahead and the next version that I'm going to upload actually has the lid opening and closing.  Please let me know which you prefer.
