### ISSUE TITLE
Wylte - playtesting notes and ideas

### ISSUE THREAD

**Issue by Wylted1** [Shoopity/MonkeyIslandPinball#8]
Nowhere else I can see to add comments, so...an "issue" it is!

Middle LeChuck shot is a little frustrating, maybe reduce coverage of Target001 and plank1
    Compared to Shoopity and VP8 version, which has a clear line of sight up that lane to LeChuck
![20210518225042_1](https://user-images.githubusercontent.com/25475953/118763571-eaa9cb00-b82c-11eb-865e-dc525862190d.jpg)

Idea for improvement to Sword Master mode - instead of timed "INSULT" targets, have Taunt Duels: have green lit targets to shoot for, and red to avoid
    hitting green letter will play a good Threepwood taunt and advance him, hitting red will give a bad taunt and advance Opponent
    Could have stages, follow duels in the game

**Comment by Shoopity** [comment]
No, this is the perfect place for these kinds of suggestions.  For the moment, I'll leave these things up to remdwaas.  I'm just the coding key for now.

My $0.02, I do find it harder to hit myself as well, but I wasn't sure if my frustration was because it's harder than it should be, or because it's just not the shot I'm used to.  A lot of tables have some kind of "main" shot to bash, and Le Chuck used to be it.  I know on this table I find myself hitting the Monkey Head a lot.  Maybe the Le Chuck shot shouldn't be as easy to hit?  Maybe it should be a left-flipper-only shot (even then it's tough)?  Just throwing out thoughts, not saying I think that's how it should be.

**Comment by remdwaas** [comment]
i changed the table to make it more playable, can you try monkeyisland6 on my google drive? I have a new issue if the ball goes out of the vulcano then it flyies trough th ramp even if i set physical walls. I hope you both can find it out what it is.

Your other sugestion: you mean the lanes  that you have to shoot. Taunt duels? i will add this as modes in the bar. I want that the bar is locked and after you play the left ramp it opens and then a slotmachine will come, so you have to collect grog beer, taunt maybe barfight but i'm not so familiar with that.

IF the ramp is fixed, then i will solve this issue. also i need feedback if it is more playable.

**Comment by remdwaas** [comment]
with the help of shoopity and JP it's fixed Wylte can you test the table so i can close the issue

**Comment by Wylted1** [comment]
Didn't expect you to slice that target off completely lol.
Much easier to hit from the left flipper, and consistent from the right.

Noticed the plank moved toward the monkey head a bit, but it never got in the way.  Love the Le Chuck/Volcano/Grog dispenser rail, too :D

"Fixed"!
